{
  "retriever": "sparse",
  "query": "In gatts_process_read_by_type_req of gatt_sr.cc, there is a possible out of bounds write due to a logic error in the code. This could lead to remote code execution with no additional execution privileges needed. User interaction is not needed for exploitation.",
  "keyphrases": {
    "rootcause": [
      "logic error in the code"
    ],
    "weakness": [
      "Out of bounds write"
    ]
  },
  "timestamp": "2025-07-12 05:21:38",
  "cve_id": "CVE-2024-49747",
  "result_count": 12,
  "results": [
    {
      "cwe_id": "131",
      "name": "Incorrect Calculation of Buffer Size",
      "score": 351.5237179243371,
      "search_source": "rootcause:logic error in the code"
    },
    {
      "cwe_id": "908",
      "name": "Use of Uninitialized Resource",
      "score": 341.159336440952,
      "search_source": "rootcause:logic error in the code"
    },
    {
      "cwe_id": "191",
      "name": "Integer Underflow (Wrap or Wraparound)",
      "score": 334.07362207501797,
      "search_source": "rootcause:logic error in the code"
    },
    {
      "cwe_id": "667",
      "name": "Improper Locking",
      "score": 319.57982708905047,
      "search_source": "rootcause:logic error in the code"
    },
    {
      "cwe_id": "362",
      "name": "Concurrent Execution using Shared Resource with Improper Synchronization ('Race Condition')",
      "score": 312.34276220531103,
      "search_source": "rootcause:logic error in the code"
    },
    {
      "cwe_id": "20",
      "name": "Improper Input Validation",
      "score": 312.0061674001939,
      "search_source": "rootcause:logic error in the code"
    },
    {
      "cwe_id": "122",
      "name": "Heap-based Buffer Overflow",
      "score": 309.82125185029116,
      "search_source": "rootcause:logic error in the code"
    },
    {
      "cwe_id": "1284",
      "name": "Improper Validation of Specified Quantity in Input",
      "score": 309.0208840112726,
      "search_source": "rootcause:logic error in the code"
    },
    {
      "cwe_id": "190",
      "name": "Integer Overflow or Wraparound",
      "score": 307.4467381671834,
      "search_source": "rootcause:logic error in the code"
    },
    {
      "cwe_id": "125",
      "name": "Out-of-bounds Read",
      "score": 306.63037096694774,
      "search_source": "weakness:Out of bounds write"
    },
    {
      "cwe_id": "248",
      "name": "Uncaught Exception",
      "score": 305.3659350158706,
      "search_source": "rootcause:logic error in the code"
    },
    {
      "cwe_id": "787",
      "name": "Out-of-bounds Write",
      "score": 298.62110353496894,
      "search_source": "weakness:Out of bounds write"
    }
  ]
}