{
  "retriever": "sparse",
  "query": "Socket.IO is an open source, real-time, bidirectional, event-based, communication framework. A specially crafted Socket.IO packet can trigger an uncaught exception on the Socket.IO server, thus killing the Node.js process. This issue is fixed by commit `15af22fc22` which has been included in `socket.io@4.6.2` (released in May 2023). The fix was backported in the 2.x branch as well with commit `d30630ba10`. Users are advised to upgrade. Users unable to upgrade may attach a listener for the error event to catch these errors.",
  "keyphrases": {
    "rootcause": [
      "uncaught exception"
    ]
  },
  "timestamp": "2025-07-13 10:29:42",
  "cve_id": "CVE-2024-38355",
  "result_count": 11,
  "results": [
    {
      "cwe_id": "248",
      "name": "Uncaught Exception",
      "score": 724.9629515587619,
      "search_source": "rootcause:uncaught exception"
    },
    {
      "cwe_id": "1284",
      "name": "Improper Validation of Specified Quantity in Input",
      "score": 494.89971451242934,
      "search_source": "rootcause:uncaught exception"
    },
    {
      "cwe_id": "201",
      "name": "Insertion of Sensitive Information Into Sent Data",
      "score": 481.66500007334713,
      "search_source": "rootcause:uncaught exception"
    },
    {
      "cwe_id": "1333",
      "name": "Inefficient Regular Expression Complexity",
      "score": 465.7114059971019,
      "search_source": "rootcause:uncaught exception"
    },
    {
      "cwe_id": "674",
      "name": "Uncontrolled Recursion",
      "score": 464.6396579306138,
      "search_source": "rootcause:uncaught exception"
    },
    {
      "cwe_id": "754",
      "name": "Improper Check for Unusual or Exceptional Conditions",
      "score": 464.5384153198412,
      "search_source": "rootcause:uncaught exception"
    },
    {
      "cwe_id": "617",
      "name": "Reachable Assertion",
      "score": 463.2664988206176,
      "search_source": "rootcause:uncaught exception"
    },
    {
      "cwe_id": "379",
      "name": "Creation of Temporary File in Directory with Insecure Permissions",
      "score": 458.8840553323375,
      "search_source": "rootcause:uncaught exception"
    },
    {
      "cwe_id": "770",
      "name": "Allocation of Resources Without Limits or Throttling",
      "score": 458.31006454156056,
      "search_source": "rootcause:uncaught exception"
    },
    {
      "cwe_id": "755",
      "name": "Improper Handling of Exceptional Conditions",
      "score": 455.9245837486378,
      "search_source": "rootcause:uncaught exception"
    },
    {
      "cwe_id": "378",
      "name": "Creation of Temporary File With Insecure Permissions",
      "score": 151.57200582615326,
      "search_source": "base_query"
    }
  ]
}