{
  "method": "sparse_rootcause_1",
  "query": "Socket.IO is an open source, real-time, bidirectional, event-based, communication framework. A specially crafted Socket.IO packet can trigger an uncaught exception on the Socket.IO server, thus killing the Node.js process. This issue is fixed by commit `15af22fc22` which has been included in `socket.io@4.6.2` (released in May 2023). The fix was backported in the 2.x branch as well with commit `d30630ba10`. Users are advised to upgrade. Users unable to upgrade may attach a listener for the error event to catch these errors.",
  "keyphrases": {
    "rootcause": "uncaught exception"
  },
  "timestamp": "2025-07-13T10:29:42.543300",
  "results_count": 10,
  "results_summary": [
    {
      "doc_id": "248",
      "name": "Uncaught Exception",
      "score": 724.9629515587619
    },
    {
      "doc_id": "1284",
      "name": "Improper Validation of Specified Quantity in Input",
      "score": 494.89971451242934
    },
    {
      "doc_id": "201",
      "name": "Insertion of Sensitive Information Into Sent Data",
      "score": 481.66500007334713
    },
    {
      "doc_id": "1333",
      "name": "Inefficient Regular Expression Complexity",
      "score": 465.7114059971019
    },
    {
      "doc_id": "674",
      "name": "Uncontrolled Recursion",
      "score": 464.6396579306138
    }
  ]
}