{
  "query": "In the Linux kernel, the following vulnerability has been resolved bpf Fail bpf_timer_cancel when callback is being cancelled Given a schedule timer1 cbtimer2 cb bpf_timer_cancel(timer2)bpf_timer_cancel(timer1) Both bpf_timer_cancel calls would wait for the other callback to finish executing, introducing a lockup. Add an atomic_t count named cancelling in bpf_hrtimer. This keeps track of all in-flight cancellation requests for a given BPF timer. Whenever cancelling a BPF timer, we must check if we have outstanding cancellation requests, and if so, we must fail the operation with an error (-EDEADLK) since cancellation is synchronous and waits for the callback to finish executing. This implies that we can enter a deadlock situation involving two or more timer callbacks executing in parallel and attempting to cancel one another. Note that we avoid incrementing the cancelling counter for the target timer (the one being cancelled) if bpf_timer_cancel is not invoked from a callback, to avoid spurious errors. The whole point of detecting cur->cancelling and returning -EDEADLK is to not enter a busy wait loop (which may or may not lead to a lockup). This does not apply in case the caller is in a non-callback context, the other side can continue to cancel as it sees fit without running into errors. Background on prior attempts Earlier versions of this patch used a bool cancelling bit and used the following pattern under timer->lock to publish cancellation status. l",
  "count": 10,
  "results": [
    {
      "cwe_id": "667",
      "name": "Improper Locking",
      "abstraction": "Class",
      "score": 994.232492835496,
      "original_score": 994.232492835496,
      "mapping_usage": "Allowed-with-Review"
    },
    {
      "cwe_id": "833",
      "name": "Deadlock",
      "abstraction": "Base",
      "score": 990.39623362765,
      "original_score": 990.39623362765,
      "mapping_usage": "Allowed"
    },
    {
      "cwe_id": "364",
      "name": "Signal Handler Race Condition",
      "abstraction": "Base",
      "score": 980.9112860880664,
      "original_score": 980.9112860880664,
      "mapping_usage": "Allowed"
    },
    {
      "cwe_id": "835",
      "name": "Loop with Unreachable Exit Condition ('Infinite Loop')",
      "abstraction": "Base",
      "score": 978.7526148372551,
      "original_score": 978.7526148372551,
      "mapping_usage": "Allowed"
    },
    {
      "cwe_id": "362",
      "name": "Concurrent Execution using Shared Resource with Improper Synchronization ('Race Condition')",
      "abstraction": "Class",
      "score": 977.7089421351882,
      "original_score": 977.7089421351882,
      "mapping_usage": "Allowed-with-Review"
    },
    {
      "cwe_id": "863",
      "name": "Incorrect Authorization",
      "abstraction": "Class",
      "score": 964.5587352191101,
      "original_score": 964.5587352191101,
      "mapping_usage": "Allowed-with-Review"
    },
    {
      "cwe_id": "287",
      "name": "Improper Authentication",
      "abstraction": "Class",
      "score": 964.3986792968939,
      "original_score": 964.3986792968939,
      "mapping_usage": "Discouraged"
    },
    {
      "cwe_id": "617",
      "name": "Reachable Assertion",
      "abstraction": "Base",
      "score": 963.6866684886255,
      "original_score": 963.6866684886255,
      "mapping_usage": "Allowed"
    },
    {
      "cwe_id": "125",
      "name": "Out-of-bounds Read",
      "abstraction": "Base",
      "score": 957.7938538398668,
      "original_score": 957.7938538398668,
      "mapping_usage": "Allowed"
    },
    {
      "cwe_id": "754",
      "name": "Improper Check for Unusual or Exceptional Conditions",
      "abstraction": "Class",
      "score": 956.6363762297519,
      "original_score": 956.6363762297519,
      "mapping_usage": "Allowed-with-Review"
    }
  ],
  "statistics": {
    "min": 956.6363762297519,
    "max": 994.232492835496,
    "mean": 972.9075882597905,
    "median": 971.1338386771491,
    "count": 10
  }
}